blank_issues_enabled: false
contact_links:
  - name: Zenoh discussion - Public
    url: https://github.com/eclipse-zenoh/roadmap/discussions
    about: Open to the Zenoh community. Share your feedback with the Zenoh team.
